version: '3.1'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8081:8080
    depends_on: 
        - db
        
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 33066:3306

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - 8000:3000



    

