version: “2"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./data:/var/lib/grafana
    user: “472”
    restart: unless-stopped