name: Serverless deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [12.x]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node modules 
      run: npm ci

    - name: Deploy 
      run: npx serverless deploy 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_SECRET: ${{ secrets.MYSQL_SECRET }}
        BUCKET: ${{ secrets.BUCKET }}



