name: Deploy to service

on:
  push:
    branches:
    - master

jobs:
  deploy:
    - name: Deploy
      runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        python-version: ${{ matrix.python-versiom}}
        
    - name: Use Node ${{matrix.node-version }} 
      uses: actions/setup-node@v1
      with:
        python-version: ${{ matrix.node-versiom}}

    - runs: npm ci
    - runs: serverless deploy 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_SECRET: ${{ secrets.MYSQL_SECRET }}
        BUCKET: ${{ secrets.BUCKET }}



